name: Testing the runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  just-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Running the shell script
        run: |
          echo "Hi, I am Runner"
